@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Oct 03 15:06:30 +0200 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto fe12c5e5219a4db396396ac24df6d83e --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot mux2_1_tb_func_synth xil_defaultlib.mux2_1_tb -log elaborate.log"
call xelab  -wto fe12c5e5219a4db396396ac24df6d83e --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot mux2_1_tb_func_synth xil_defaultlib.mux2_1_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
