webtalk_init -webtalk_dir C:/VIVADO-PROJECTS/13_ROBERTSON_SIM/13_ROBERTSON_SIM.sim/sim_1/behav/xsim/xsim.dir/mrob_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 20 11:32:57 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a2c6cc29-2d99-421f-b5aa-73cdbdfe79f4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e8fe9d51a28f400891889d978552d54e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "57" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2803 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7420_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3992625551 -regid "" -xml C:/VIVADO-PROJECTS/13_ROBERTSON_SIM/13_ROBERTSON_SIM.sim/sim_1/behav/xsim/xsim.dir/mrob_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/VIVADO-PROJECTS/13_ROBERTSON_SIM/13_ROBERTSON_SIM.sim/sim_1/behav/xsim/xsim.dir/mrob_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/VIVADO-PROJECTS/13_ROBERTSON_SIM/13_ROBERTSON_SIM.sim/sim_1/behav/xsim/xsim.dir/mrob_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
